---
title: "E-mini Strategies"
output: html_notebook
---

Initiate IB API connection

IBrokersRef() to get IBrokers R-API reference

```{r}
source('utils/utils.R')
tws.conn = twsConnect(clientId = 1, port = 7496)
```

Check the current portfolio value

```{r}
acct = reqAccountUpdates(tws.conn)
twsPortfolioValue(acct)
```

Retrieve e-mini data

```{r}
expiry.month = '201809'

tws.future.ym = twsFuture('YM', exch='ECBOT', expiry=expiry.month, multiplier='5')
tws.future.nq = twsFuture('NQ', exch='GLOBEX', expiry=expiry.month, multiplier='20')
tws.future.es = twsFuture('ES', exch='GLOBEX', expiry=expiry.month, multiplier='50')

tws.future.ixb = twsFuture('IXB', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Materials
tws.future.ixe = twsFuture('IXE', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Energy
tws.future.ixi = twsFuture('IXI', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Industrial
tws.future.ixm = twsFuture('IXM', exch='GLOBEX', expiry=expiry.month, multiplier='250') # Financial
tws.future.ixr = twsFuture('IXR', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Consumer Staples
tws.future.ixt = twsFuture('IXT', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Technology
tws.future.ixu = twsFuture('IXU', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Utilities
tws.future.ixv = twsFuture('IXV', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Health Care
tws.future.ixy = twsFuture('IXY', exch='GLOBEX', expiry=expiry.month, multiplier='100') # Consumer Discretionary

tws.contracts = list(tws.future.ym, tws.future.nq, tws.future.es)
mkt.data = x.ib.getHistoricalData(tws.conn, tws.contracts, start.date = '20180620', barSize = '30 secs', whatToShow = 'TRADES', useRTH = "0")
```

Data checking

```{r}
# Gaps in time
mkt.data[, .N, by=.(date, intv)][N != mkt.data[,uniqueN(symbol)], paste(date, intv, ': expected', mkt.data[,uniqueN(symbol)], 'securities but only found', N)]
# Invalid value (OHLC-Vlm)
rbindlist(lapply(c('open','high','low','close','volume'), function(item){
    mkt.data[order(get(item))][, rbind(.SD[1][, .(item=paste(item, '.min', sep=''), value=get(item), date, intv)], 
                                       .SD[nrow(.SD)][, .(item=paste(item, '.max', sep=''), value=get(item), date, intv)]), by=symbol]
}), use.names = TRUE, fill = TRUE)[order(symbol)]
# Sanity check 1: When volume is zero, OHLC should be exactly the same
mkt.data[(volume == 0) & ((open != high) | (high != low) | (low != close)),]
# Sanity check 2: L <= O,C <= H
mkt.data[(high < low) | (close < low) | (close > high) | (open < low) | (open > high),]
```

Data processing

```{r}
mkt.data[, ret := c(NA, close[-1]) / c(NA, close[-length(close)]) - 1, by = symbol]
mkt.data[, session := 1][intv > '160000', session := 2][intv < '093000', session := 0] # session = 0,1,2 for pre-open, rth, post-close
```

Stats

```{r}
# Mean & StDev of return
mkt.data[, .(mean.close = meanNA(close), mean.ret = meanNA(ret), sd.ret = sdNA(ret)), by=symbol]
# Range within Bin

# Cumulative Return
mkt.data[, idx := 1:nrow(.SD), by=symbol]
gp = ggplot(melt(mkt.data[!is.na(ret), .(idx,ret=cumprod(ret+1)-1), by=symbol], id.vars = c('idx','symbol')), aes(x=idx, y=value, color=symbol))+geom_line()
print(gp)
```

Mean-reverting Strategies

```{r}
# Enter a buy 300 below close to see if it gets picked up overnight

```

Momentum Strategies

```{r}
#
```

Disconnect

```{r}
twsDisconnect(tws.conn)
```



